package a77777_888.me.t.domain.dataentities.vacancy

import a77777_888.me.t.domain.dataentities.IVacancy
import com.google.gson.annotations.SerializedName

data class VacancyResponseEntity(
    override val id: String,
    @SerializedName("name") override val name: String,
    override val salary: Salary?,
    override val employer: Employer,
    @SerializedName("area") override val placedArea: Area,
    @SerializedName("published_at") override val publishedAt: String,
    override val experience: Experience,
    override val employment: Employment,
    override val schedule: Schedule?,
    @SerializedName("accept_temporary") override val acceptTemporary: Boolean?,
    override val description: String,
    @SerializedName("alternate_url") override val alternateUrl: String,
//    val accept_handicapped: Boolean,
//    val accept_incomplete_resumes: Boolean,
//    val accept_kids: Boolean,
//    val address: Any,
//    val allow_messages: Boolean,
//    val apply_alternate_url: String,
//    val archived: Boolean,
//    val billing_type: BillingType,
//    val branded_description: Any,
//    val code: Any,
//    val contacts: Any,
//    val created_at: String,
//    val department: Any,
//    val driver_license_types: List<Any>,
//    val has_test: Boolean,
//    val hidden: Boolean,
//    val initial_created_at: String,
//    val insider_interview: Any,
//    val key_skills: List<KeySkill>,
//    val languages: List<Any>,
//    val negotiations_url: Any,
//    val premium: Boolean,
//    val professional_roles: List<ProfessionalRole>,
//    val quick_responses_allowed: Boolean,
//    val relations: List<Any>,
//    val response_letter_required: Boolean,
//    val response_url: Any,
//    val specializations: List<Specialization>,
//    val suitable_resumes_url: Any,
//    val test: Any,
//    val type: Type,
//    val vacancy_constructor_template: Any,
//    val working_days: List<Any>,
//    val working_time_intervals: List<WorkingTimeInterval>,
//    val working_time_modes: List<WorkingTimeMode>
) : IVacancy